// generated by stringer -type EventType; DO NOT EDIT

package main

import "fmt"

const _EventType_name = "StartOfRunEndOfRunStartOfRunFilesEndOfRunFilesStartOfBurstEndOfBurstPhysicsEventCalibrationEventEventFormatErrorStartOfDataEndOfDataSystemSoftwareTriggerEventDetectorSoftwareTriggerEventSyncEvent"

var _EventType_index = [...]uint8{0, 10, 18, 33, 46, 58, 68, 80, 96, 112, 123, 132, 158, 186, 195}

func (i EventType) String() string {
	i -= 1
	if i >= EventType(len(_EventType_index)-1) {
		return fmt.Sprintf("EventType(%d)", i+1)
	}
	return _EventType_name[_EventType_index[i]:_EventType_index[i+1]]
}
